In [1]:
import sklearn
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

/home/shashank/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/shashank/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/shashank/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/shashank/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/shashank/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/shashank/anaconda3/lib/python

In [2]:
df=pd.read_csv("./spambase.data")

In [3]:
df

word_freq_make           word_freq_address        word_freq_all  \
0               0.00                        0.64                 0.64   
1               0.21                        0.28                 0.50   
2               0.06                        0.00                 0.71   
3               0.00                        0.00                 0.00   
4               0.00                        0.00                 0.00   
5               0.00                        0.00                 0.00   
6               0.00                        0.00                 0.00   
7               0.00                        0.00                 0.00   
8               0.15                        0.00                 0.46   
9               0.06                        0.12                 0.77   
10              0.00                        0.00                 0.00   
11              0.00                        0.00                 0.25   
12              0.00                        0.69                 0.34   
13              0.00                        0.00                 0.00   
14              0.00                        0.00                 1.42   
15              0.00                        0.42                 0.42   
16              0.00                        0.00                 0.00   
17              0.00                        0.00                 0.00   
18              0.00                        0.00                 0.55   
19              0.00                        0.63                 0.00   
20              0.00                        0.00                 0.00   
21              0.05                        0.07                 0.10   
22              0.00                        0.00                 0.00   
23              0.00                        0.00                 0.00   
24              0.00                        0.00                 0.00   
25              0.05                        0.07                 0.10   
26              0.00                        0.00                 0.00   
27              0.00                        0.00                 0.00   
28              0.00                        0.00                 0.00   
29              0.00                        0.00                 0.00   
...              ...                         ...                  ...   
4571            0.00                        0.00                 0.46   
4572            0.00                        0.00                 0.00   
4573            0.00                        0.00                 0.18   
4574            0.29                        0.00                 0.29   
4575            0.00                        0.00                 0.00   
4576            0.00                        0.00                 0.00   
4577            0.00                        0.00                 1.20   
4578            0.00                        0.00                 0.40   
4579            0.27                        0.05                 0.10   
4580            0.00                        0.00                 0.00   
4581            0.00                        0.00                 0.00   
4582            0.00                        0.00                 0.00   
4583            0.00                        0.00                 1.23   
4584            0.00                        0.00                 0.45   
4585            0.00                        0.00                 0.00   
4586            0.00                        0.00                 0.00   
4587            0.00                        0.00                 0.00   
4588            0.00                        0.00                 3.03   
4589            0.00                        0.00                 0.00   
4590            0.00                        0.00                 0.00   
4591            0.00                        0.00                 0.00   
4592            0.00                        0.00                 1.25   
4593            0.00                        0.00                

In [4]:
X=df.iloc[:,:-1].values

In [5]:
y=df.iloc[:,-1].values

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [49]:
# Grid Search CV
classifier=RandomForestClassifier()


In [50]:
param_grid={'n_estimators':[10,20,30,40],'criterion':['gini','entropy'],'min_samples_split':[2,3,4,5]}
grid=GridSearchCV(classifier,param_grid=param_grid,cv=20)

In [51]:
grid.fit(X_train,y_train)

GridSearchCV(cv=20, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_estimators': [10, 20, 30, 40], 'criterion': ['gini', 'entropy'], 'min_samples_split': [2, 3, 4, 5]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [52]:
grid.best_params_

{'criterion': 'entropy', 'min_samples_split': 4, 'n_estimators': 40}

In [53]:
y_pred=grid.predict(X_test)

In [56]:
cm=confusion_matrix(y_test,y_pred)

In [57]:
cm

array([[559,  22],
       [ 29, 311]])

## 2nd Method

In [7]:
from sklearn.svm import SVC

In [9]:
svc=SVC()
param_grid={'C':[1,2,3],'kernel':['rbf'],'degree':[2,3]}
gridsvc=GridSearchCV(svc,param_grid=param_grid,cv=10)

In [10]:
gridsvc.fit(X_train,y_train)

GridSearchCV(cv=10, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1, 2, 3], 'kernel': ['rbf'], 'degree': [2, 3]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [11]:
gridsvc.best_params_

{'C': 3, 'degree': 2, 'kernel': 'rbf'}

In [12]:
y_pred=gridsvc.predict(X_test)

In [13]:
cm=confusion_matrix(y_test,y_pred)

In [14]:
cm

array([[487,  85],
       [ 39, 310]])

## 3rd Method 

In [23]:
adaclass=AdaBoostClassifier()
param_grid={'n_estimators':[50,60,70],'learning_rate':[0.0001,0.001,0.1,1.0]}
gridada=GridSearchCV(adaclass,param_grid=param_grid,cv=20)

In [24]:
gridada.fit(X_train,y_train)

GridSearchCV(cv=20, error_score='raise',
       estimator=AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'n_estimators': [50, 60, 70], 'learning_rate': [0.0001, 0.001, 0.1, 1.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [26]:
y_pred=gridada.predict(X_test)

In [27]:
cm=confusion_matrix(y_test,y_pred)

In [28]:
cm

array([[529,  43],
       [ 18, 331]])